version: "3.0"
   
services:
    web:
        build: .
        container_name: site
        working_dir: /code
        command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8081"
        volumes:
            - .:/code
        ports:
            - 8081:8081
        depends_on:
            - db
    db:
        image: postgres:12.7-alpine
        container_name: banco
        restart: always
        ports:
            - 5432:5432
        environment:
              - POSTGRES_DB=registra
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=Oliveir@25
              
        volumes:
            - ./db/postgres:/var/lib/postgresql/data/