# Generated by Django 4.1 on 2022-09-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_User',
            fields=[
                ('usuario', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=64)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
